<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\CRC.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\CRC.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Cursors\Cross1.cur" />
    <Resource Include="Resources\Images\Close.png" />
    <Resource Include="Resources\Images\Connect.png" />
    <Resource Include="Resources\Images\Copy.png" />
    <Resource Include="Resources\Images\Delete.png" />
    <Resource Include="Resources\Images\DisplaySettings.png" />
    <Resource Include="Resources\Images\Edit.png" />
    <Resource Include="Resources\Images\Export.png" />
    <Resource Include="Resources\Images\Help.png" />
    <Resource Include="Resources\Images\LoadProfile.png" />
    <Resource Include="Resources\Images\Maximize.png" />
    <Resource Include="Resources\Images\MaximizeMinimize.png" />
    <Resource Include="Resources\Images\Menu.png" />
    <Resource Include="Resources\Images\Minimize.png" />
    <Resource Include="Resources\Images\NewProfile.png" />
    <Resource Include="Resources\Images\QuestionBlue.png" />
    <Resource Include="Resources\Images\QuestionRed.png" />
    <Resource Include="Resources\Images\Rename.png" />
    <Resource Include="Resources\Images\SaveProfileAs.png" />
    <Resource Include="Resources\Images\Settings.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GeoJSON.Net" Version="1.4.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SkiaSharp" Version="3.116.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.116.1" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Resources\Themes\Dark.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Resources\Controls\Styles.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Resources\Controls\Templates.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
